nemo_path: /mnt/sdb/ebakhturina/nemo_ckpts/punctuation/2021.nemo/Punctuation_Capitalization_with_BERT_base_uncased.nemo
punct_label_ids:
  O: 0
  ',': 1
  .: 2
  '?': 3
capit_label_ids:
  O: 0
  U: 1
class_labels:
  punct_labels_file: punct_label_ids.csv
  capit_labels_file: capit_label_ids.csv
dataset:
  data_dir: punct_dataset_complete
  max_seq_length: 128
  pad_label: O
  ignore_extra_tokens: false
  ignore_start_end: false
  use_cache: true
  num_workers: 2
  pin_memory: false
  drop_last: false
train_ds:
  text_file: text_train.txt
  labels_file: labels_train.txt
  shuffle: true
  num_samples: -1
  batch_size: 64
validation_ds:
  ds_item: null
  text_file: text_dev.txt
  labels_file: labels_dev.txt
  shuffle: false
  num_samples: -1
  batch_size: 64
test_ds:
  ds_item: null
  text_file: text_dev.txt
  labels_file: labels_dev.txt
  shuffle: false
  num_samples: -1
  batch_size: 64
tokenizer:
  tokenizer_name: bert-base-uncased
  vocab_file: tokenizer.vocab_file
  tokenizer_model: null
  special_tokens: null
language_model:
  pretrained_model_name: bert-base-uncased
  lm_checkpoint: null
  config_file: bert-base-uncased_encoder_config.json
  config: null
punct_head:
  punct_num_fc_layers: 1
  fc_dropout: 0.1
  activation: relu
  use_transformer_init: true
capit_head:
  capit_num_fc_layers: 1
  fc_dropout: 0.1
  activation: relu
  use_transformer_init: true
optim:
  name: adam
  lr: 0.0001
  weight_decay: 0.0
  sched:
    name: WarmupAnnealing
    warmup_steps: null
    warmup_ratio: 0.1
    last_epoch: -1
    monitor: val_loss
    reduce_on_plateau: false
target: nemo.collections.nlp.models.token_classification.punctuation_capitalization_model.PunctuationCapitalizationModel
